head:
  name: "OneLayerHead"
  hidden_size_m: 1
  middle_features: null

target_cols:
  - content
  - wording

pool:
  name: "ConcatenatePooling"
  params:
    n_last_layers: 4

base_transformer: roberta-base
config_path: null

num_targets: 2

data:
  train_path: data/${fold_id}/train.csv
  val_path: data/${fold_id}/test.csv
  test_path: data/${fold_id}/test.csv

criterion:
  name: RMSELoss

learning_rate: 0.001

optim:
  name: "Adam"
  params: null

reinit_head_layer: False


scheduler:
  name: ReduceLROnPlateau
  params:
    mode: min


fold_id: 3b9047
batch_size: 8
max_epochs: 1
run_name: 'another_exp7'
max_length: 512
gradient_accumulation_steps: 1
val_check_intervals: 100
freeze_backbone: False
logger: tensorboard